#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_PATH="$ROOT_DIR/venv"

if [ -f "$VENV_PATH/bin/activate" ] && [ -z "$VIRTUAL_ENV" ]; then
    source "$VENV_PATH/bin/activate"
    PYTHON_EXEC="python"
else
    PYTHON_EXEC="python3"
fi

NAME=ll-connect-wireless
ALIAS=llcw

eval "$($PYTHON_EXEC "$ROOT_DIR/src/parseArg.py" "$@")"

cat <<EOF > "$ROOT_DIR/src/vars.py"
# Generated by compile.sh - DO NOT EDIT MANUALLY
APP_NAME = "$NAME"
APP_ALIAS = "$ALIAS"
APP_VERSION = "$VERSION"
APP_RELEASE = $RELEASE
APP_RC = $RC
APP_RAW_VERSION = "$RAW_VERSION"
EOF

# Export variables for compile.sh and the RPM spec
export NAME ALIAS COMPILE_VER VERSION RELEASE RC RAW_TAG ROOT_DIR