#!/usr/bin/env bash

NAME=ll-connect-wireless
ALIAS=llcw
VERSION=$(date +%Y%m%d.%H%M)
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --releaseVer)
            if [ -n "$2" ]; then
                VERSION="$2"
                shift
            fi
            ;;
    esac
    shift
done

cat <<EOF > "$ROOT_DIR/src/vars.py"
# Generated by compile.sh - DO NOT EDIT MANUALLY
APP_NAME = "$NAME"
APP_ALIAS = "$ALIAS"
APP_VERSION = "$VERSION"
EOF

export NAME ALIAS VERSION ROOT_DIR